project:
  type: website
  output-dir: docs
website:
  search:
    type: textbox 
  open-graph: true
  title: "Home"
  navbar:
    right:
      - text: "About"
        href: Content/About/index.qmd
      - text: "Projects"
        href: Content/Projects/index.qmd
      - text: "Blog"
        href: Content/Blog/index.qmd
      - text: "Talks"
        href: Content/Talks/index.qmd
      - text: "Resources"
        href: Content/Resources/index.qmd
      
  page-footer:
    left:
      - href: https://www.quarto.org
        text: Made with quarto®
      - href: https://chatgpt.com/
        text: Built with ChatGPT®
    right: 
      - href: Content/License/index.qmd
        text: License 
      - icon: linkedin
        href: https://www.linkedin.com/in/oluwaseunfowotade/
      - icon: github
        href: https://github.com/Fowotadeseun/
      - icon: envelope-fill
        href: mailto:fowotadeoluwaseun15@gmail.com
format:
  html:
    theme: cosmo
    fontsize: 1.1em
    linestretch: 1.7
    citations-hover: true
    footnotes-hover: true
    theme: Assets/Themes/MainThemeBCA.scss
    highlight-style: github-dark
editor: visual